workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - nayab99@gmail.com
